[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn", "python311Packages.uvicorn"]

[phases.install]
cmds = [
    "python -m venv --system-site-packages .venv",
    ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = ".venv/bin/python -m gunicorn backend.app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
